# Generated by Django 4.2.3 on 2023-08-10 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_remove_person_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
